export const ErrorCodes = {
  //Auth ve User Hataları
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  OLD_PASSWORD_INCORRECT: 'OLD_PASSWORD_INCORRECT',
  //Grup ve Konuşma Hataları
  CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
  NOT_CONVERSATION_PARTICIPANT: 'NOT_CONVERSATION_PARTICIPANT',
  NOT_GROUP_CONVERSATION: 'NOT_GROUP_CONVERSATION',
  GROUP_MIN_PARTICIPANTS_REQUIRED: 'GROUP_MIN_PARTICIPANTS_REQUIRED',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  ALREADY_GROUP_PARTICIPANT: 'ALREADY_GROUP_PARTICIPANT',
  CANNOT_LEAVE_AS_OWNER: 'CANNOT_LEAVE_AS_OWNER',
  GROUP_NOT_PUBLIC: 'GROUP_NOT_PUBLIC',
  //Mesaj Hataları
  MESSAGE_NOT_FOUND: 'MESSAGE_NOT_FOUND',
  CANNOT_EDIT_OTHERS_MESSAGE: 'CANNOT_EDIT_OTHERS_MESSAGE',
  CANNOT_DELETE_OTHERS_MESSAGE: 'CANNOT_DELETE_OTHERS_MESSAGE',
  MESSAGE_TOO_LONG: 'MESSAGE_TOO_LONG',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  FILE_REQUIRED: 'FILE_REQUIRED',
};
